
services:
  bot:
    build:
      context: .
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    restart: always
    volumes:
      - ./logs:/app/logs
      - ./alembic:/app/alembic
    ports:
      - '8000:8000'
    command: >
      sh -c "alembic upgrade head &&
             python main.py"


  db:
    image: postgres:alpine
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: blue_btn_db
    env_file:
      - .env
    ports:
      - '5435:5432'
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:5-alpine
    restart: on-failure
    volumes:
      - redis-data:/data
    ports:
      - '6377:6379'

volumes:
  postgres-data:
  redis-data:
